### ISSUE TITLE
Game crashes when loading world in 1.18

### ISSUE THREAD

**Issue by Givoric** [Globox1997/Dehydration#64] opened 2021-12-26 16:01 UTC
From what i have read in the log it seems to be an issue with dehydration mixins. If it is not like that i apologise
crash log: https://pastebin.com/pyFG2DxA

**Comment by 0x6273** [comment] 2021-12-28 08:11
This is a duplicate of #58. You'll have to pick either Dehydration or Origins. In 1.18 they are not compatible.

**Comment by Globox1997** [comment] 2022-01-06 11:18
Referencing #58

**Closed as completed by Globox1997** 2022-01-06 11:18 UTC
